# This file was generated by GoReleaser. DO NOT EDIT.
cask "aster" do
  name "aster"
  desc "Terminal disk usage analyzer for macOS"
  homepage "https://github.com/mobanhawi/aster"
  version "0.5.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aster"

  on_macos do
    on_intel do
      url "https://github.com/mobanhawi/aster/releases/download/v#{version}/aster_darwin_x86_64.tar.gz"
      sha256 "c1def54536b46e10512245e5791df38419bd15b277158c1fcddf808b254b1674"
    end
    on_arm do
      url "https://github.com/mobanhawi/aster/releases/download/v#{version}/aster_darwin_arm64.tar.gz"
      sha256 "69a8a6f88c3ceb23dd00de74107f820682527657ef593a8de7bebe5bf06e579d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/aster"]
    end
  end

  # No zap stanza required
end
