# This file was generated by GoReleaser. DO NOT EDIT.
cask "aster" do
  name "aster"
  desc "Terminal disk usage analyzer for macOS"
  homepage "https://github.com/mobanhawi/aster"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aster"

  on_macos do
    on_intel do
      url "https://github.com/mobanhawi/aster/releases/download/v#{version}/aster_darwin_x86_64.tar.gz"
      sha256 "20c3afcb8dc3dd27aca6a4da95d86184fcc03e517198c6445aa709c0657f0d8d"
    end
    on_arm do
      url "https://github.com/mobanhawi/aster/releases/download/v#{version}/aster_darwin_arm64.tar.gz"
      sha256 "611c60f66d5ca92cc9bf123537d6e603cda1be28b49a421a232c3ba55dabeaa1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/aster"]
    end
  end

  # No zap stanza required
end
