# This file was generated by GoReleaser. DO NOT EDIT.
cask "aster" do
  name "aster"
  desc "Terminal disk usage analyzer for macOS"
  homepage "https://github.com/mobanhawi/aster"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aster"

  on_macos do
    on_intel do
      url "https://github.com/mobanhawi/aster/releases/download/v#{version}/aster_darwin_x86_64.tar.gz"
      sha256 "96f27c8b27c6cdfc8273e7ae32c7b5c020d94d34b3c017e908a58305a9c399ed"
    end
    on_arm do
      url "https://github.com/mobanhawi/aster/releases/download/v#{version}/aster_darwin_arm64.tar.gz"
      sha256 "cc4927e9b94bc81f7a8f5d0305e5c2be5254906d17d2f514cf8ce155735e16b0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/aster"]
    end
  end

  # No zap stanza required
end
